# Generated by Django 5.2.9 on 2026-07-09 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('metric', models.CharField(help_text='Column name to aggregate', max_length=100, verbose_name='Metric')),
                ('aggregation', models.CharField(choices=[('sum', 'Sum'), ('avg', 'Average'), ('count', 'Count'), ('min', 'Minimum'), ('max', 'Maximum')], default='count', max_length=20, verbose_name='Aggregation')),
                ('condition', models.CharField(choices=[('above', 'Above'), ('below', 'Below'), ('equals', 'Equals'), ('change_percent', 'Percent Change')], max_length=20, verbose_name='Condition')),
                ('threshold', models.FloatField(verbose_name='Threshold')),
                ('check_interval', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20, verbose_name='Check Interval')),
                ('notification_channels', models.JSONField(default=list, help_text="List of channels: 'email', 'webhook'", verbose_name='Notification Channels')),
                ('webhook_url', models.URLField(blank=True, help_text='URL to POST alert payload when triggered', verbose_name='Webhook URL')),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Optional dataset filters applied before aggregation', verbose_name='Filters')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('last_checked', models.DateTimeField(blank=True, null=True, verbose_name='Last Checked')),
                ('last_triggered', models.DateTimeField(blank=True, null=True, verbose_name='Last Triggered')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='datasets.dataset', verbose_name='Dataset')),
                ('recipients', models.ManyToManyField(blank=True, related_name='data_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Recipients')),
            ],
            options={
                'verbose_name': 'Data Alert',
                'verbose_name_plural': 'Data Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, verbose_name='Triggered At')),
                ('actual_value', models.FloatField(verbose_name='Actual Value')),
                ('threshold', models.FloatField(verbose_name='Threshold')),
                ('condition', models.CharField(max_length=20, verbose_name='Condition')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='Notification Sent')),
                ('notification_response', models.JSONField(blank=True, null=True, verbose_name='Notification Response')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='alerts.dataalert', verbose_name='Alert')),
            ],
            options={
                'verbose_name': 'Alert History',
                'verbose_name_plural': 'Alert Histories',
                'ordering': ['-triggered_at'],
            },
        ),
    ]
