# Generated by Django 5.2.9 on 2026-07-11 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboards', '0003_dashboard_is_public_dashboardpermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('email_html', 'HTML Email')], default='pdf', max_length=20, verbose_name='Format')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20, verbose_name='Frequency')),
                ('day_of_week', models.IntegerField(blank=True, help_text='0=Monday, 6=Sunday (for weekly)', null=True, verbose_name='Day of Week')),
                ('day_of_month', models.IntegerField(blank=True, help_text='1-31 (for monthly)', null=True, verbose_name='Day of Month')),
                ('time', models.TimeField(verbose_name='Time')),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='Timezone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('last_sent', models.DateTimeField(blank=True, null=True, verbose_name='Last Sent')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='Next Run')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to='dashboards.dashboard', verbose_name='Dashboard')),
                ('recipients', models.ManyToManyField(blank=True, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL, verbose_name='Recipients')),
            ],
            options={
                'verbose_name': 'Scheduled Report',
                'verbose_name_plural': 'Scheduled Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
