# Generated by Django 5.2.9 on 2026-07-11 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent At')),
                ('recipients_count', models.IntegerField(default=0, verbose_name='Recipients')),
                ('format', models.CharField(default='email_html', max_length=20, verbose_name='Format')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Error')),
                ('rendered_html', models.TextField(blank=True, verbose_name='Rendered HTML')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='PDF File')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='reports.scheduledreport', verbose_name='Report')),
            ],
            options={
                'verbose_name': 'Report History',
                'verbose_name_plural': 'Report History',
                'ordering': ['-sent_at'],
            },
        ),
    ]
