# Generated by Django 5.2.9 on 2026-07-11 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('source_type', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('sqlite', 'SQLite'), ('api', 'REST API'), ('csv', 'CSV File')], max_length=20, verbose_name='Source Type')),
                ('connection_config', models.JSONField(blank=True, default=dict, help_text='Host, port, database, credentials etc.', verbose_name='Connection Config')),
                ('sync_schedule', models.CharField(blank=True, help_text="Cron expression or 'hourly'/'daily'/'weekly'", max_length=100, verbose_name='Sync Schedule')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('last_synced', models.DateTimeField(blank=True, null=True, verbose_name='Last Synced')),
                ('status', models.CharField(choices=[('active', 'Active'), ('error', 'Error'), ('syncing', 'Syncing')], default='active', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Data Source',
                'verbose_name_plural': 'Data Sources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='Started At')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished At')),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], max_length=20, verbose_name='Status')),
                ('rows_imported', models.IntegerField(default=0, verbose_name='Rows Imported')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='datasources.datasource', verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
