# Generated by Django 5.2.9 on 2026-07-11 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='connection_config',
            field=models.JSONField(blank=True, default=dict, help_text='Host, port, database, credentials etc. Stored encrypted at rest.', verbose_name='Connection Config'),
        ),
        migrations.CreateModel(
            name='CSVImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='File Name')),
                ('file_path', models.CharField(blank=True, max_length=512, verbose_name='File Path')),
                ('rows_total', models.IntegerField(default=0, verbose_name='Total Rows')),
                ('rows_imported', models.IntegerField(default=0, verbose_name='Rows Imported')),
                ('rows_failed', models.IntegerField(default=0, verbose_name='Rows Failed')),
                ('error_log', models.JSONField(blank=True, default=list, help_text='Array of {row, error} objects', verbose_name='Error Log')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_import_jobs', to='datasources.datasource', verbose_name='Source')),
            ],
            options={
                'verbose_name': 'CSV Import Job',
                'verbose_name_plural': 'CSV Import Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
