# Generated by Django 5.2.9 on 2026-07-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0002_add_csvimportjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='auto_sync_enabled',
            field=models.BooleanField(default=False, help_text='Enable automatic data synchronization on schedule', verbose_name='Auto Sync Enabled'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='csv_config',
            field=models.JSONField(blank=True, default=dict, help_text='CSV-specific settings: delimiter, encoding, has_header, etc.', verbose_name='CSV Config'),
        ),
    ]
