[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
python_files = test_*.py *_tests.py tests.py
testpaths = .
addopts = -v --tb=short --cov=core --cov=alerts --cov=charts --cov=dashboards --cov=datasets --cov=datasources --cov=reports --cov=management --cov-report=term-missing --cov-fail-under=40