# Generated by Django 5.2.9 on 2026-07-08 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('chart_type', models.CharField(choices=[('bar', 'Bar'), ('line', 'Line'), ('pie', 'Pie'), ('scatter', 'Scatter'), ('area', 'Area'), ('heatmap', 'Heatmap')], max_length=50, verbose_name='Chart Type')),
                ('config', models.JSONField(default=dict, help_text='Chart configuration: x_axis, y_axis, group_by, filters, etc.', verbose_name='Config')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_charts', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='datasets.dataset', verbose_name='Dataset')),
            ],
            options={
                'verbose_name': 'Chart',
                'verbose_name_plural': 'Charts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('sql', models.TextField(verbose_name='SQL Query')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_queries', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_queries', to='datasets.dataset', verbose_name='Dataset')),
            ],
            options={
                'verbose_name': 'Saved Query',
                'verbose_name_plural': 'Saved Queries',
                'ordering': ['-created_at'],
            },
        ),
    ]
