# Generated by Django 5.2.9 on 2026-07-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_add_gauge_funnel_treemap_radar'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='drill_down_config',
            field=models.JSONField(blank=True, default=dict, help_text='Drill-down configuration: enabled, target_chart_id, target_dashboard_id, drill_column, pass_filters', verbose_name='Drill-down Config'),
        ),
    ]
