# Generated by Django 5.1.6

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0003_chart_drill_down_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChartAnnotation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(verbose_name="Text")),
                ("x_value", models.CharField(blank=True, max_length=255, verbose_name="X Value")),
                ("y_value", models.FloatField(blank=True, null=True, verbose_name="Y Value")),
                ("color", models.CharField(default="#ef4444", max_length=20, verbose_name="Color")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("chart", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="annotations", to="charts.chart", verbose_name="Chart")),
            ],
            options={
                "verbose_name": "Chart Annotation",
                "verbose_name_plural": "Chart Annotations",
                "ordering": ["created_at"],
            },
        ),
    ]