"""
Django settings for team_backend project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import json
from datetime import timedelta
from pathlib import Path
from zoneinfo import ZoneInfo
import environ

# Override Django's default JSON encoder globally
from django.core.serializers.json import DjangoJSONEncoder


env = environ.Env(DATABASE_URL=(str, None))


class DjangoZoneInfoJSONEncoder(DjangoJSONEncoder):
    """Django JSON encoder that handles ZoneInfo objects."""

    def default(self, o):
        if isinstance(o, ZoneInfo):
            return str(o)
        return super().default(o)


# Monkey patch Django's JSON encoder
import django.core.serializers.json

django.core.serializers.json.DjangoJSONEncoder = DjangoZoneInfoJSONEncoder

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "change-this-in-production")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third party
    "rest_framework",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "corsheaders",
    "django_celery_beat",
    "django_celery_results",
    "import_export",
    "rest_framework_simplejwt.token_blacklist",
    # Local apps
    "management",
    # BI Dashboard apps
    "datasets",
    "charts",
    "dashboards",
    "query",
    "alerts",
    "reports",
    "datasources",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "core.middleware.HTTPMethodRestrictionMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "core.middleware.APILanguageDetectionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.api_language",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASE_URL = env("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {"default": env.db()}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
#         "OPTIONS": {"min_length": 6},
#     },
#     {
#         "NAME": "core.utils.validators.StrongPasswordValidator",
#     },
# ]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "fa"

LANGUAGES = [
    ("fa", "Persian"),
    ("en", "English"),
]

LOCALE_PATHS = [
    BASE_DIR / "locale",
]

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = False

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom User Model
# AUTH_USER_MODEL = "accounts.User"

# Admin URL Path (configurable for security)
ADMIN_URL_PATH = os.environ.get("ADMIN_URL_PATH", "admin/")

# REST Framework
REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "core.base_exception.custom_exception_handler",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "core.utils.pagination.CustomPagination",
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.OrderingFilter",
        "rest_framework.filters.SearchFilter",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": os.environ.get("THROTTLE_RATE_ANON", "100/hour"),
        "user": os.environ.get("THROTTLE_RATE_USER", "1000/hour"),
    },
}

# JWT Settings
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=int(os.environ.get("JWT_ACCESS_TOKEN_LIFETIME_MINUTES", 60))
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=int(os.environ.get("JWT_REFRESH_TOKEN_LIFETIME_DAYS", 1))
    ),
    "ROTATE_REFRESH_TOKENS": os.environ.get("JWT_ROTATE_REFRESH_TOKENS", "true").lower()
    == "true",
    "BLACKLIST_AFTER_ROTATION": os.environ.get(
        "JWT_BLACKLIST_AFTER_ROTATION", "true"
    ).lower()
    == "true",
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
}

# DRF Spectacular - Fully offline using SIDECAR (bundled files)
SPECTACULAR_SETTINGS = {
    "TITLE": "Team Backend API",
    "DESCRIPTION": "API for team management system",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SCHEMA_PATH_PREFIX": "/api/",
    "COMPONENT_SPLIT_REQUEST": True,
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "docExpansion": "none",
        "operationsSorter": "alpha",
        "tagsSorter": "alpha",
        "tryItOutEnabled": True,
        "displayRequestDuration": True,
        "filter": True,
        "showExtensions": True,
        "layout": "BaseLayout",
    },
    "REDOC_DIST": "SIDECAR",
    "REDOC_UI_SETTINGS": {
        "theme": {
            "typography": {
                "fontFamily": "\"-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif\"",
            }
        }
    },
    "REDOC_UI_TEMPLATE_NAME": "drf_spectacular/redoc.html",
    "POSTPROCESSING_HOOKS": [
        "core.schema.add_global_lang_param",
    ],
}

# CORS
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

CORS_ALLOW_CREDENTIALS = True

# Security Settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

# Celery Configuration
# https://docs.celeryproject.org/en/stable/django/first-steps-with-django.html
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.environ.get(
    "CELERY_RESULT_BACKEND", "redis://localhost:6379/0"
)
CELERY_TIMEZONE = os.environ.get("CELERY_TIMEZONE", "UTC")
CELERY_TASK_TRACK_STARTED = (
    os.environ.get("CELERY_TASK_TRACK_STARTED", "true").lower() == "true"
)
CELERY_TASK_TIME_LIMIT = int(os.environ.get("CELERY_TASK_TIME_LIMIT", 3600))
CELERY_TASK_SOFT_TIME_LIMIT = int(os.environ.get("CELERY_TASK_SOFT_TIME_LIMIT", 3300))
CELERY_WORKER_PREFETCH_MULTIPLIER = int(
    os.environ.get("CELERY_WORKER_PREFETCH_MULTIPLIER", 1)
)
CELERY_WORKER_MAX_TASKS_PER_CHILD = int(
    os.environ.get("CELERY_WORKER_MAX_TASKS_PER_CHILD", 1000)
)


# Custom JSON Encoder to handle ZoneInfo objects
class ZoneInfoJSONEncoder(json.JSONEncoder):
    """Custom JSON encoder that handles ZoneInfo objects."""

    def default(self, o):
        if isinstance(o, ZoneInfo):
            return str(o)
        return super().default(o)


# Celery Beat Settings
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# Celery serialization settings to handle ZoneInfo objects
from kombu.serialization import register

register(
    "json",
    lambda obj: json.dumps(obj, cls=ZoneInfoJSONEncoder),
    lambda obj: json.loads(obj),
    content_type="application/json",
    content_encoding="utf-8",
)
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]

# Data source encryption key (Fernet 32-byte urlsafe-base64)
DATASOURCE_ENCRYPTION_KEY = os.environ.get(
    "DATASOURCE_ENCRYPTION_KEY",
    "dykR7b9exTCqrIEN_vpvZdepJMN_qzpp7eS9ZdLW1RQ=",
)

# Reports periodic task
CELERY_BEAT_SCHEDULE = {
    "generate-scheduled-reports": {
        "task": "reports.tasks.generate_scheduled_reports",
        "schedule": 3600.0,  # every hour
        "options": {"queue": "celery"},
    },
    "sync-datasources": {
        "task": "datasources.tasks.sync_all_due_sources",
        "schedule": 600.0,  # every 10 minutes
        "options": {"queue": "celery"},
    },
}

# Celery task routing - dedicated queue for activity logging
CELERY_TASK_ROUTES = {
    "activity_log.tasks.log_activity_async": {"queue": "activity_logs"},
    "api.tasks.cleanup_s3_temp_files": {"queue": "celery4"},
}

# Celery queue definitions
CELERY_TASK_DEFAULT_QUEUE = "celery"
CELERY_TASK_QUEUES = {
    "celery": {
        "exchange": "celery",
        "exchange_type": "direct",
        "routing_key": "celery",
    },
    "activity_logs": {
        "exchange": "activity_logs",
        "exchange_type": "direct",
        "routing_key": "activity_logs",
    },
}

# APM Configuration (conditionally enabled)
APM_SERVICE_NAME = os.environ.get("APM_SERVICE_NAME")
APM_SERVER_URL = os.environ.get("APM_SERVER_URL")
APM_SECRET_TOKEN = os.environ.get("APM_SECRET_TOKEN")
APM_ENVIRONMENT = os.environ.get("APM_ENVIRONMENT", "development")

if APM_SERVICE_NAME and APM_SERVER_URL:
    INSTALLED_APPS.append("elasticapm.contrib.django")

    ELASTIC_APM = {
        "SERVICE_NAME": APM_SERVICE_NAME,
        "SECRET_TOKEN": APM_SECRET_TOKEN,
        "SERVER_URL": APM_SERVER_URL,
        "ENVIRONMENT": APM_ENVIRONMENT,
        "DISABLE_SEND": False,
        "LOG_LEVEL": "WARNING",
        "DJANGO_AUTO_INSTRUMENT": True,
        "CAPTURE_BODY": "errors" if DEBUG else "off",
        "CAPTURE_HEADERS": True,
        "FILTER_FUNCTIONS": [],
        "TRANSACTIONS_IGNORE_PATTERNS": [
            r"^OPTIONS ",
            r"^HEAD ",
        ],
    }

    # Add APM middleware if APM is enabled
    MIDDLEWARE.insert(0, "elasticapm.contrib.django.middleware.TracingMiddleware")


import json as builtin_json

# Monkey patch the builtin json.dumps to use our encoder
original_dumps = builtin_json.dumps


def patched_dumps(obj, **kwargs):
    if "cls" not in kwargs:
        kwargs["cls"] = ZoneInfoJSONEncoder
    return original_dumps(obj, **kwargs)


builtin_json.dumps = patched_dumps

# Logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "celery": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Web Push Notifications - VAPID keys
# Generate these using: python -c "from pywebpush import vapid; vapid.generate_vapid_keypair()"
VAPID_PRIVATE_KEY = os.environ.get("VAPID_PRIVATE_KEY", "")
VAPID_PUBLIC_KEY = os.environ.get("VAPID_PUBLIC_KEY", "")
VAPID_CLAIMS = {
    "sub": f"mailto:{os.environ.get('VAPID_EMAIL', 'admin@example.com')}",
}


SSE_SERVER = os.environ.get("SSE_SERVER", True)

S3_CLEANUP_HOURS = os.environ.get("S3_CLEANUP_HOURS", True)
