# Generated by Django 5.2.9 on 2026-07-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='filters',
            field=models.JSONField(blank=True, default=list, help_text='Global filter definitions: [{id, name, type, column, dataset, defaultValue, options}]', verbose_name='Filters'),
        ),
    ]
